### ISSUE TITLE
EPIC: Opruimen oude DNS structuur

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/dns-management#152]
Doel: We hebben na de verhuizingen van de oude naar de nieuwe landingzone alleen nog maar de csp-nijmegen.nl domein naam in de oude landingzone staan. Deze moet verplaatst worden naar het gn-nijmegen account.

Status:

- Huidige landingzone heeft een csp-nijmegen.nl hosted zone in het gn-network account
- De oude landingzone heeft een csp-nijmegen.nl hosted zone in het dns account
- De production branch van het dns-management project wordt uitgerold naar de OUDE landingzone
- De main branch van het dns-management project wordt uitgerold naar de NIEUWE landingzone
- De csp-nijmegen.nl domein naam staat al geregistreerd in gn-network (nieuw landingzone)

Stappen plan DNS:

- Verhuizen csp-nijmegen.nl domein naam naar gn-network account in nieuwe landingzone (dit kan zonder downtime, zie stap 1 van https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-transfer-between-aws-accounts.html)
- Checken of voor alle subdomeinen (1 per account) een NS en DS record bestaat in de csp-nijmegen.nl hosted zone van de NIEUWE landingzone (let op deze is dus nog niet live)
- Updaten van nameservers voor de csp-nijmegen.nl domain naam naar de nameservers van de csp-nijmegen.nl hosted zone in de nieuwe landingzone
- Wachten tot NS wijziging overal is doorgevoerd
- Checken of de subdomeinen live zijn (mocht dit niet zo zijn, snel de nameservers terug veranderen (rollback))
- Gelukt!

Opruimen:

- undeployen dns-management-production pipeline in oude landingzone
- Verwijderen production branch
- Verwijderen dns records uit oude hosted zone
- Verwijderen dns-management stacks in dns account

```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/154
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/153
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/160
- [x] [DNS] Informatie inwinnen over hoe de migratie zonder downtime te kunnen doen
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/161
```
```[tasklist]
### DNS migratie ('s nachts)
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/162
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/163
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/164
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/165
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/166
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/167
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/168
- [ ] https://github.com/GemeenteNijmegen/dns-management/issues/169
```

**Comment by marnixdessing** [comment]
SOA records en NS record TTL values van csp-nijmegen.nl records zijn nu teruggezet naar 1 minuut

**Comment by marnixdessing** [comment]
Verschillen van oud naar nieuw (ontbreekt in nieuw)

   [
      'Record not in new hostedzone _2db6a8de32f9fb49b42f88127092be93.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _321fee2a85eecdd51af4f0f43f85a506.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _340cfc157601acb6b4c252db633edc14.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _578630817267b977076c44d1065f484d.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _7b3cf064cfc7fdbd40a7c6677563c523.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _82e96918e2e006569edd57a9bf2ca18a.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _83670523e9ab46362639ca116fa1b1ef.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _8bcedded666ccd9b575ab5d78840b91a.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _9098af4bf46f252af5e3a050f3393016.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _9a7010aac50ae002ee6511d0f0755330.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _c09af98dc2fe54695443bf987e37c329.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone 3oauc4kfqwgwdmd7sqyj66r4lwx52gbd._domainkey.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone jscft5y6jlalacyyubloeajrxeaezfbb._domainkey.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone p2qzrb7orqvnmcbfteuitb6rcm7ppjeg._domainkey.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone accp.csp-nijmegen.nl. of DS',
      'Record not in new hostedzone accp.csp-nijmegen.nl. of NS',
      'Record not in new hostedzone auth-prod.csp-nijmegen.nl. of DS',
      'Record not in new hostedzone auth-prod.csp-nijmegen.nl. of NS',
      'Record not in new hostedzone _76e4569991b509964584cb63698e1d66.esf-accp.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone _21ef7078d93987b2d49b2d89223723b7.esf-prod.csp-nijmegen.nl. of CNAME',
      'Record not in new hostedzone generiek-accp.csp-nijmegen.nl. of NS',
      'Record not in new hostedzone generiek-prod.csp-nijmegen.nl. of NS',
      'Record not in new hostedzone mail.csp-nijmegen.nl. of MX',
      'Record not in new hostedzone mail.csp-nijmegen.nl. of TXT',
      'Record not in new hostedzone sandbox.csp-nijmegen.nl. of NS',
      'Record not in new hostedzone test-2.csp-nijmegen.nl. of NS',
      'Record not in new hostedzone test-3.csp-nijmegen.nl. of NS',
      'Record not in new hostedzone test-4.csp-nijmegen.nl. of NS',
      'Record not in new hostedzone um-demo.csp-nijmegen.nl. of NS'
    ]

**Comment by marnixdessing** [comment]
ns-67.awsdns-08.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

**Comment by marnixdessing** [comment]
Tests uitgevoerd. Nieuw plan gemaakt: we gaan componenten lost trekken (tijdelijk) en de migratie 's nachts doen. Nieuwe tasklist gemaakt.

**Comment by marnixdessing** [comment]
Migratie is afgerond, pipeline is opgeruimd en oud branch is opgeslagen als backup.
